### ISSUE TITLE
Parsing markdown output

### ISSUE THREAD

**Issue by leemachin** [emacs-lsp/lsp-ruby#4]
Solargraph seems to only output markdown formatted strings. If you're using lsp-ui then you get popups full of unparsed markdown, and some other kind of parsing that I'm not sure behaves as it should.

I'm not sure if this is an issue for lsp/lsp-ui itself but I don't see the same issue with Go.

![](https://user-images.githubusercontent.com/736291/45380619-0334a280-b5fb-11e8-8917-f5c5ddce58b4.png)

I would be delighted to offer a solution to this myself, but is this the right place?

**Comment by gpittarelli** [comment]
I have a WIP solution to this. It is unfortunately a bit deeper than just an lsp-ruby change (involves lsp-mode and maybe also lsp-ui)

What is important to the lsp-ruby package is what to do with those `solargraph:...` urls. Even if we turn them into links they

**Comment by pcmantz** [comment]
I am still experiencing this behavior. I know this repository is outdated; should I reopen this bug in `lsp-mode`?

**Comment by gpittarelli** [comment]
Yeah you should switch to using lsp-mode without this package and reopen the bug their.
